config/routes.rb
Rails.application.routes.draw do
	root 'home#index'
	resources :contacts
	resources :users
  
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_NUMBER_REGEX = /[0-9]+/i
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :contacts
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, presence: true, length: { maximum: 30 }
  validates :phone_number, presence: true,
                           length: { maximum: 15 }
  mount_uploader :contact_photo, ContactPhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
	has_many :contacts
	before_save { email.downcase! }
	validates :name, presence: true, length: { minimum: 5, maximum: 55 }
	validates :email, presence: true, length: { maximum: 50 }, 
																		format: { with: VALID_EMAIL_REGEX },
																		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6, maximum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  	def logged_in_user
  		unless user_logged_in?
  			store_location
  			flash[:danger] = "Please Login"
  			redirect_to login_path
  		end
  	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :logged_in_user
	def index
    if params[:category].blank?
		  @contacts = current_user.contacts
    else
      @category_id = Category.find_by(name: params[:category]).id
      @contacts = current_user.contacts.where(:category_id => @category_id)
    end  
	end

	def new
		@contact = current_user.contacts.build
    @categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def edit
		@contact = current_user.contacts.find(params[:id])
    @categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def create
		@contact = current_user.contacts.build(contact_params)
    @contact.category_id = params[:category_id]

		if @contact.save
			flash[:success] = "Contact created successfully"
			redirect_to contacts_path
		else
			render 'new'
		end
	end

	def update
		@contact = current_user.contacts.find(params[:id])
    @contact.category_id = params[:category_id]
		if @contact.update(contact_params)
			flash[:success] = "Contact Updated Successfully"
			redirect_to contacts_path
		else
			render	'edit'
		end
	end

  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.delete
    redirect_to contacts_path
  end


	private
		def contact_params
			params.require(:contact).permit(:name, :phone_number, :email, :category_id, :contact_photo)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
 		user = User.find_by(email: params[:session][:email].downcase)
 		if user && user.authenticate(params[:session][:password])
      log_in(user)
 			flash[:success] = "Hey!! #{user.name}, Welcome back"
 			redirect_back_or root_path
 		else
 			flash.now[:danger] = 'Invalid email/password combination'
 			render 'new'
 		end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      log_in @user
      flash[:success] = "welcome #{@user.name}! You have successfully Registered "
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def user_logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def redirect_back_or(default)
  	redirect_to(session[:return_to] || default)
  	session.delete(:return_to)
	end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/edit.html.erb
<%= provide(:title, "Signup") %>
<div class="errors col-md-6 col-md-offset-2">
	<% if @contact.errors.any? %>
		<p class="alert alert-danger"><%= pluralize(@contact.errors.count, 'error') %> stopped you from saving you contact</p>
			<ul>
			<% @contact.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>
</div>

<div class="col-md-8 col-md-offset-4">
	<%= form_for (@contact) do |f| %>
    <%= f.select :category_id, @categories %>
    
		<div class=" input-group">
			<%= f.label :name %><br/>
			<%= f.text_field :name, class: "form-control" %>
		</div>
		
		<div class=" input-group">
			<%= f.label :phone_number %><br/>
			<%= f.text_field :phone_number, class: "form-control" %>
		</div>

		<div class=" input-group">
			<%= f.label :email %><br/>
			<%= f.email_field :email, class: "form-control" %>
		</div>

    <div class="input-group">
      <%= f.label :contact_photo %><br/>
      <%= f.file_field :contact_photo, class: "form-control" %>
    </div>
		<br/>

		<%= f.submit "save", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/contacts/index.html.erb
<%= provide(:title, "Contacts") %>
<% if user_logged_in? %>
  <div class="filter"> 
    <ul>
      Filter:
      <li class="<%= "active" if params[:category].blank? %>">
      <%= link_to "All", contacts_path %>
      </li>
      <% Category.all.each do |category| %>
      <li class="<%= "active" if params[:category] == category.name %>">
      <%= link_to category.name, contacts_path(category: category.name) %>
      </li>
      <% end %>
    </ul>
  </div>
  <% if @contacts.count == 0 %>
    <h3>You don't have any contacts in <%= params[:category] %> category</h3>
  <% else %>  
  	<h2 class="text-center">Your Contacts</h2>
    <% @contacts.each do |contact| %>
    	<div class="contact_single col-md-3">
    			<%= image_tag(contact.contact_photo_url(:thumb).to_s) %>
          <h4>Name: <%= contact.name %></h4>
    			<h4>Mobile No: <%= contact.phone_number %></h4>
          <% if contact.email? %><h4>Email: <%= contact.email %></h4><% end %>
    			<h4>Category: 
          <% if contact.category_id == 1 %>
          Family
          <% elsif contact.category_id == 2 %>
          Work
          <% elsif contact.category_id == 3 %>
          Friends
          <% elsif contact.category_id == 4 %>
          Others
          <% end %>
          </h4>
    			<ul class="contact_options">
            <%= link_to "Edit", edit_contact_path(contact) %>
            <%= link_to "Delete", contact_path(contact), method: :delete, data: { confirm: "Are you sure"} %>
    			</ul>
    	</div>
    <% end %>
  <% end %>  
<% else %>
	<h4>You are not authorized to view this content. Signup or login to view your contacts</h4>	
<% end %>	

app/views/contacts/new.html.erb
<%= provide(:title, "Signup") %>
<div class="errors col-md-6 col-md-offset-2">
	<% if @contact.errors.any? %>
		<p class="alert alert-danger"><%= pluralize(@contact.errors.count, 'error') %> stopped you from saving you contact</p>
			<ul>
			<% @contact.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>
</div>

<div class="col-md-8 col-md-offset-4">
	<%= form_for (@contact) do |f| %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Pick a Category") %>
		<div class="input-group">
			<%= f.label :name %><br/>
			<%= f.text_field :name, class: "form-control" %>
		</div>

		<div class="input-group">
			<%= f.label :phone_number %><br/>
			<%= f.text_field :phone_number, class: "form-control" %>
		</div>

		<div class="input-group">
      <%= f.label :email %><br/>
      <%= f.email_field :email, class: "form-control" %>
    </div>

    <div class="input-group">
			<%= f.label :contact_photo %><br/>
			<%= f.file_field :contact_photo, class: "form-control" %>
		</div>
		<br/>

		<%= f.submit "save", class: "btn btn-primary" %>
	<% end %>
</div>

app/views/home/index.html.erb
<%= provide(:title, "Home") %>
<h1 class="main_heading text_center">Welcome to ContactBook</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= yield(:title) %> | ContactBook | One place for all your contacts</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">ContactBook</a>
				</div>
				<ul class="nav navbar-nav navbar-right">
					<% if user_logged_in? %>
						<li><%= link_to "Create New Contact", new_contact_path %></li>
						<li><a href="/contacts">My Contacts</a></li>
						<li><%= link_to "Logout", logout_path, method: :delete, data: { confirm: 'Are you sure??' }, class: "navbar-right" %></li>
					<% else %>
						<li><a class="navbar-right" href="/signup">Signup</a></li>
						<li><a class="navbar-right" href="/login">Login</a></li>
					<% end %>
				</ul>
			</div>
		</nav>
		<div class="container">
			<% flash.each do |message_type, message| %>
  			<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/users/new.html.erb
<%= provide(:title, "Signup") %>
<div class="errors col-md-6 col-md-offset-2">
	<% if @user.errors.any? %>
		<p class="alert alert-danger"><%= pluralize(@user.errors.count, 'error') %> stopped you from being signed up</p>
			<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
	<% end %>
</div>

<div class="col-md-8 col-md-offset-4">
	<%= form_for (@user) do |f| %>
		<div class=" input-group">
			<%= f.label :name %><br/>
			<%= f.text_field :name, class: "form-control" %>
		</div>

		<div class=" input-group">
			<%= f.label :email %><br/>
			<%= f.email_field :email, class: "form-control" %>
		</div>

		<div class=" input-group">
			<%= f.label :password %><br/>
			<%= f.password_field :password, class: "form-control" %>
		</div>

		<div class=" input-group">
			<%= f.label :password_confirmation %><br/>
			<%= f.password_field :password_confirmation, class: "form-control" %>
		</div>
		<br/>

		<%= f.submit "Signup", class: "btn btn-primary" %>
	<% end %>
</div>